"""类型定义模块"""

from wecom_aibot.types.config import WSClientOptions, Logger, BotConfig, BotStatus
from wecom_aibot.types.message import (
    MessageType,
    BaseMessage,
    TextMessage,
    ImageMessage,
    MixedMessage,
    VoiceMessage,
    FileMessage,
    VideoMessage,
    TextContent,
    ImageContent,
    VoiceContent,
    FileContent,
    VideoContent,
    MixedContent,
    MixedMsgItem,
    MessageFrom,
    QuoteContent,
)
from wecom_aibot.types.event import (
    EventType,
    EventMessage,
    EventFrom,
    EventContent,
    EnterChatEvent,
    TemplateCardEventData,
    FeedbackEventData,
)
from wecom_aibot.types.api import (
    WsCmd,
    WsFrame,
    WsFrameHeaders,
    StreamReplyBody,
    ReplyMsgItem,
    ReplyFeedback,
    WelcomeTextReplyBody,
    WelcomeTemplateCardReplyBody,
    SendMarkdownMsgBody,
    SendTemplateCardMsgBody,
    WSClientEventMap,
    # 媒体上传类型
    WeComMediaType,
    VideoOptions,
    UploadMediaOptions,
    UploadMediaFinishResult,
)
from wecom_aibot.types.template_card import (
    TemplateCardType,
    TemplateCard,
    TemplateCardSource,
    TemplateCardActionMenu,
    TemplateCardMainTitle,
    TemplateCardEmphasisContent,
    TemplateCardQuoteArea,
    TemplateCardHorizontalContent,
    TemplateCardJumpAction,
    TemplateCardAction,
    TemplateCardVerticalContent,
    TemplateCardImage,
    TemplateCardImageTextArea,
    TemplateCardSubmitButton,
    TemplateCardSelectionItem,
    TemplateCardButton,
    TemplateCardCheckbox,
)

__all__ = [
    # Config types
    "WSClientOptions",
    "Logger",
    "BotConfig",
    "BotStatus",
    # Message types
    "MessageType",
    "BaseMessage",
    "TextMessage",
    "ImageMessage",
    "MixedMessage",
    "VoiceMessage",
    "FileMessage",
    "VideoMessage",
    "TextContent",
    "ImageContent",
    "VoiceContent",
    "FileContent",
    "VideoContent",
    "MixedContent",
    "MixedMsgItem",
    "MessageFrom",
    "QuoteContent",
    # Event types
    "EventType",
    "EventMessage",
    "EventFrom",
    "EventContent",
    "EnterChatEvent",
    "TemplateCardEventData",
    "FeedbackEventData",
    # API types
    "WsCmd",
    "WsFrame",
    "WsFrameHeaders",
    "StreamReplyBody",
    "ReplyMsgItem",
    "ReplyFeedback",
    "WelcomeTextReplyBody",
    "WelcomeTemplateCardReplyBody",
    "SendMarkdownMsgBody",
    "SendTemplateCardMsgBody",
    "WSClientEventMap",
    # 媒体上传类型
    "WeComMediaType",
    "VideoOptions",
    "UploadMediaOptions",
    "UploadMediaFinishResult",
    # Template card types
    "TemplateCardType",
    "TemplateCard",
    "TemplateCardSource",
    "TemplateCardActionMenu",
    "TemplateCardMainTitle",
    "TemplateCardEmphasisContent",
    "TemplateCardQuoteArea",
    "TemplateCardHorizontalContent",
    "TemplateCardJumpAction",
    "TemplateCardAction",
    "TemplateCardVerticalContent",
    "TemplateCardImage",
    "TemplateCardImageTextArea",
    "TemplateCardSubmitButton",
    "TemplateCardSelectionItem",
    "TemplateCardButton",
    "TemplateCardCheckbox",
]
